name: sse_client
description: >-
  Provides client and server functionality for setting up bi-directional
  communication through Server Sent Events (SSE) and corresponding POST
  requests.
version: 0.1.1
homepage: https://www.github.com/jamiewest/sse_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  stream_channel: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
